spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties.hibernate.format_sql: true

springdoc:
  swagger-ui:
    persist-authorization: true
    default-models-expand-depth: -1
    path: /api-docs
